### ISSUE TITLE
An error while trying to import the words

### ISSUE THREAD

**Issue by Erlemar** [prz3m/kind2anki#14]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-14.0-arm64-arm-64bit
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-10-03 09:00:22
Add-ons possibly involved: ⁨kind2anki - import words from Kindle Vocabulary Builder⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/andreylukyanenko/Library/Application Support/Anki2/addons21/1621749993/__init__.py", line 130, in accept
    self.mw.reset()
  File "aqt.main", line 822, in reset
  File "aqt.main", line 774, in _synthesize_op_did_execute_from_reset
  File "_aqt.hooks", line 3620, in __call__
  File "aqt.deckchooser", line 120, in on_operation_did_execute
  File "aqt.deckchooser", line 82, in _update_button_label
RuntimeError: wrapped C/C++ object of type QPushButton has been deleted

**Comment by prz3m** [comment]
Hi, thanks for reporting. Unfortunately I haven't updated the add on to support Anki Qt6 variant, it should work with Anki Qt5 though. I'm going to fix it as soon as I find some time.
