### ISSUE TITLE
Not working with Anki update

### ISSUE THREAD

**Issue by jberlinger** [prz3m/kind2anki#15]
Think there might be an issue since a recent Anki update.

Debug info:
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.4.1-arm64-arm-64bit

When loading kind2anki - import words from Kindle Vocabulary Builder:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/Users/jberlinger/Library/Application Support/Anki2/addons21/1621749993/__init__.py", line 8, in <module>
    from PyQt5.QtCore import QThread, pyqtSignal
ModuleNotFoundError: No module named 'PyQt5'

**Comment by prz3m** [comment]
Hi, thanks for reporting this. Sadly I haven't had time to update this add-on to Qt6 yet. It should still work with Anki Qt5 version though.

I can't say when, but I'll do my best to get this sorted before Anki ditches Qt5 completely.

**Comment by TheCloud** [comment]
I would be glad to help...
https://addon-docs.ankiweb.net/qt.html

**Comment by prz3m** [comment]
It took too long, but the fix is merged
